# Generated by Django 5.1.6 on 2025-03-14 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_department_description'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.DeleteModel(
            name='FakeModel',
        ),
        migrations.AddField(
            model_name='teacher',
            name='departments',
            field=models.ManyToManyField(related_name='teachers', to='academics.department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='hire_date',
            field=models.DateField(default=datetime.date(1999, 1, 1)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
