# Generated by Django 5.1.6 on 2025-03-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_student_grade_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='guardians',
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='students', to='users.parent'),
        ),
    ]
