# Generated by Django 5.1.6 on 2025-03-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_student_guardians_student_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='relationship_to_student',
        ),
        migrations.AlterField(
            model_name='staff',
            name='hire_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='stakeholder_types',
            field=models.ManyToManyField(related_name='stakeholders', to='users.stakeholdertype'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
