# Generated by Django 5.1.6 on 2025-03-13 23:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('registration_number', models.CharField(help_text="Accreditor's unique ID", max_length=100, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('accreditation_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Pending', 'Pending')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, unique=True)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to=core.models.school_logo_upload_path)),
                ('school_motto', models.CharField(blank=True, max_length=255, null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('principal_name', models.CharField(max_length=255)),
                ('social_media_links', models.JSONField(blank=True, help_text='Store links as JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accreditation_details', models.ManyToManyField(blank=True, related_name='schools', to='core.accreditor')),
            ],
        ),
    ]
