# Generated by Django 5.1.6 on 2025-03-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='max_age',
            field=models.PositiveIntegerField(default=18, help_text='Maximum age for learners'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='min_age',
            field=models.PositiveIntegerField(default=6, help_text='Minimum age for learners'),
        ),
    ]
