# Generated by Django 5.1.1 on 2025-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_schoolsettings_max_age_schoolsettings_min_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='core/image/school_photo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
