# Generated by Django 5.1.1 on 2025-03-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
