# Generated by Django 5.1.6 on 2025-03-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_fakemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FakeModel',
        ),
        migrations.AddField(
            model_name='coursetype',
            name='abbreviation',
            field=models.CharField(default='GEN', max_length=10),
            preserve_default=False,
        ),
    ]
