# Generated by Django 5.1.6 on 2025-03-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_delete_fakemodel_coursetype_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='abbreviation',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
