# Generated by Django 5.1.6 on 2025-03-15 13:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_coursetype_abbreviation'),
        ('users', '0002_remove_teacher_department_delete_fakemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('stream', models.CharField(max_length=5)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentprogression',
            name='from_year',
        ),
        migrations.RemoveField(
            model_name='studentprogression',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentprogression',
            name='to_year',
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='classsubject',
            name='unique_class_subject',
        ),
        migrations.RemoveField(
            model_name='studentsubjectenrollment',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentsubjectenrollment',
            name='subject',
        ),
        migrations.AlterField(
            model_name='subject',
            name='course_code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Course code must be in the format 'AAA-111'.", regex='^[A-Za-z]{3}-\\d{3}$')]),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_group', 'subject')},
        ),
        migrations.AddField(
            model_name='promotion',
            name='from_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='academics.classgroup'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='users.student'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='to_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='academics.classgroup'),
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classgroup'),
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.student'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.classgroup'),
        ),
        migrations.AddField(
            model_name='subjectassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='studentsubjectenrollment',
            name='subject_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.subjectassignment'),
        ),
        migrations.DeleteModel(
            name='StudentEnrollment',
        ),
        migrations.DeleteModel(
            name='StudentProgression',
        ),
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('academic_year', 'grade', 'stream')},
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='classroom',
        ),
        migrations.AlterUniqueTogether(
            name='studentclassenrollment',
            unique_together={('student', 'class_group')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together={('class_group', 'subject')},
        ),
    ]
