# Generated by Django 5.1.6 on 2025-03-15 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_delete_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('numeric_level', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['numeric_level'],
            },
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.gradelevel'),
        ),
    ]
