# Generated by Django 5.1.6 on 2025-03-15 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_gradelevel_alter_classgroup_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.gradestream'),
        ),
    ]
