# Generated by Django 5.1.6 on 2025-03-17 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_remove_studentsubjectenrollment_subject_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubjectenrollment',
            name='subject',
        ),
        migrations.AddField(
            model_name='classsubject',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentsubjectenrollment',
            name='class_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.classsubject'),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.classgroup'),
        ),
    ]
